<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>RobotControllerTemplate</AssemblyName>
    <RootNamespace>RobotControllerTemplate</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AOI_Monitor\AOI_Monitor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="robot_controller_manifest.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
