namespace AOI_Monitor.Models;

public enum MesIntegrationMode
{
    NotConnected,
    MockRest,
    FutureProduction,
}

public sealed class MesIntegrationSettings
{
    public MesIntegrationMode Mode { get; set; } = MesIntegrationMode.NotConnected;
    public string MockEndpointUrl { get; set; } = string.Empty;
    public int UploadTimeoutSeconds { get; set; } = 10;

    public bool IsMockRest => Mode == MesIntegrationMode.MockRest;
}

public sealed class TraceabilityPayload
{
    public string SchemaVersion { get; set; } = "1.0.0";
    public string IntegrationMode { get; set; } = "Mock REST";
    public string LotId { get; set; } = string.Empty;
    public string BoardModel { get; set; } = string.Empty;
    public string? SerialNumber { get; set; }
    public string StationId { get; set; } = string.Empty;
    public string OperatorId { get; set; } = string.Empty;
    public string Result { get; set; } = "REVIEW";
    public DateTime TimestampUtc { get; set; } = DateTime.UtcNow;
    public string DefectSummary { get; set; } = string.Empty;
    public string ImagePath { get; set; } = string.Empty;
    public string OverlayPath { get; set; } = string.Empty;
    public string InspectionEngine { get; set; } = string.Empty;
    public string ModelVersion { get; set; } = string.Empty;
    public double Confidence { get; set; }
    public double Score { get; set; }
    public string SourceNotice { get; set; } = "Mock MES integration payload generated by AOI Monitor PoC. Not production MES writeback.";
}

public sealed record MesUploadAttemptRecord(
    long Id,
    DateTime CreatedAtUtc,
    string Mode,
    string EndpointUrl,
    string PayloadPath,
    string Status,
    string Message,
    string OperatorId,
    string LotId,
    string BoardModel,
    string Result);
