namespace AOI_Monitor.Models;

public enum MesIntegrationMode
{
    NotConnected,
    MockRest,
    FutureProduction,
    Rest,
}

public enum MesRestAuthMode
{
    None,
    ApiKey,
    Bearer,
    Basic,
}

public class MesRestSettings
{
    public MesIntegrationMode Mode { get; set; } = MesIntegrationMode.NotConnected;
    public string MockEndpointUrl { get; set; } = string.Empty;
    public int UploadTimeoutSeconds { get; set; } = 10;
    public bool AutoUploadEnabled { get; set; }
    public string BaseUrl { get; set; } = string.Empty;
    public string UploadResultPath { get; set; } = "/api/aoi/results";
    public string UploadImagePath { get; set; } = "/api/aoi/images";
    public MesRestAuthMode AuthMode { get; set; } = MesRestAuthMode.None;
    public string ApiKeyHeaderName { get; set; } = "X-API-Key";
    public string ApiKey { get; set; } = string.Empty;
    public string BearerToken { get; set; } = string.Empty;
    public string Username { get; set; } = string.Empty;
    public string Password { get; set; } = string.Empty;
    public int TimeoutSeconds { get; set; } = 10;
    public int MaxRetryCount { get; set; } = 2;
    public int RetryBackoffMs { get; set; } = 500;

    public bool IsRest => Mode == MesIntegrationMode.Rest;
}

public sealed class MesIntegrationSettings : MesRestSettings
{
    public bool IsMockRest => Mode == MesIntegrationMode.MockRest;
    public bool IsUploadCapable => Mode is MesIntegrationMode.MockRest or MesIntegrationMode.Rest;
}

public sealed class TraceabilityPayload
{
    public string SchemaVersion { get; set; } = "1.0.0";
    public string IntegrationMode { get; set; } = "Mock REST";
    public string LotId { get; set; } = string.Empty;
    public string BoardModel { get; set; } = string.Empty;
    public string? SerialNumber { get; set; }
    public string StationId { get; set; } = string.Empty;
    public string OperatorId { get; set; } = string.Empty;
    public string Result { get; set; } = "REVIEW";
    public DateTime TimestampUtc { get; set; } = DateTime.UtcNow;
    public string DefectSummary { get; set; } = string.Empty;
    public List<string> DefectCodes { get; set; } = new();
    public string ImagePath { get; set; } = string.Empty;
    public string OverlayPath { get; set; } = string.Empty;
    public string InspectionEngine { get; set; } = string.Empty;
    public string ModelVersion { get; set; } = string.Empty;
    public double Confidence { get; set; }
    public double Score { get; set; }
    public string SourceNotice { get; set; } = "Mock MES integration payload generated by AOI Monitor PoC. Not production MES writeback.";
}

public sealed record MesUploadAttemptRecord(
    long Id,
    DateTime CreatedAtUtc,
    string Mode,
    string EndpointUrl,
    string PayloadPath,
    string Status,
    string Message,
    string OperatorId,
    string LotId,
    string BoardModel,
    string Result);

public sealed record MesSpoolQueueRecord(
    long Id,
    DateTime CreatedAtUtc,
    DateTime? LastAttemptAtUtc,
    DateTime? NextAttemptAtUtc,
    string PayloadType,
    string PayloadJson,
    string PayloadPath,
    string EndpointUrl,
    int RetryCount,
    int MaxRetryCount,
    string Status,
    string LastError,
    string OperatorId,
    string LotId,
    string BoardModel,
    string Result);

public sealed record MesSpoolRetrySummary(
    int Attempted,
    int Succeeded,
    int Failed);

public sealed class MesUploadResponseContract
{
    public bool Accepted { get; set; }
    public string Message { get; set; } = string.Empty;
    public string ExternalInspectionId { get; set; } = string.Empty;
    public DateTime TimestampUtc { get; set; } = DateTime.UtcNow;
    public string ResultCode { get; set; } = string.Empty;
}

public sealed class MesReadinessCriteria
{
    public bool FailOnPendingQueue { get; set; }
    public bool FailOnFailedQueue { get; set; } = true;
    public int MaximumPendingAgeMinutes { get; set; } = 60;
    public bool RequirePassingTraceabilityTest { get; set; }
}

public sealed class MesReadinessSummary
{
    public string Status { get; set; } = "MES Not Configured";
    public string Mode { get; set; } = "Not Connected";
    public int PendingCount { get; set; }
    public int FailedCount { get; set; }
    public int SentCount { get; set; }
    public int AbandonedCount { get; set; }
    public int OldPendingCount { get; set; }
    public string LatestTraceabilityTestStatus { get; set; } = "NOT RUN";
    public List<string> Messages { get; set; } = new();
}

public sealed class TraceabilityTestReport
{
    public long Id { get; set; }
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
    public string Status { get; set; } = "FAIL";
    public string Mode { get; set; } = "Not Connected";
    public string EndpointUrl { get; set; } = string.Empty;
    public string ResultStatus { get; set; } = "FAIL";
    public string ImageStatus { get; set; } = "NOT SENT";
    public string PayloadPath { get; set; } = string.Empty;
    public string ReportJsonPath { get; set; } = string.Empty;
    public string ReportHtmlPath { get; set; } = string.Empty;
    public string Message { get; set; } = string.Empty;
    public bool ProductionModeConfirmed { get; set; }
    public string OperatorId { get; set; } = "UNKNOWN";
}
