namespace AOI_Monitor.Models;

public enum MesIntegrationMode
{
    NotConnected,
    MockRest,
    FutureProduction,
    Rest,
}

public enum MesRestAuthMode
{
    None,
    ApiKey,
    Bearer,
    Basic,
}

public class MesRestSettings
{
    public MesIntegrationMode Mode { get; set; } = MesIntegrationMode.NotConnected;
    public string MockEndpointUrl { get; set; } = string.Empty;
    public int UploadTimeoutSeconds { get; set; } = 10;
    public bool AutoUploadEnabled { get; set; }
    public string BaseUrl { get; set; } = string.Empty;
    public string UploadResultPath { get; set; } = "/api/aoi/results";
    public string UploadImagePath { get; set; } = "/api/aoi/images";
    public MesRestAuthMode AuthMode { get; set; } = MesRestAuthMode.None;
    public string ApiKeyHeaderName { get; set; } = "X-API-Key";
    public string ApiKey { get; set; } = string.Empty;
    public string BearerToken { get; set; } = string.Empty;
    public string Username { get; set; } = string.Empty;
    public string Password { get; set; } = string.Empty;
    public int TimeoutSeconds { get; set; } = 10;
    public int MaxRetryCount { get; set; } = 2;
    public int RetryBackoffMs { get; set; } = 500;

    public bool IsRest => Mode == MesIntegrationMode.Rest;
}

public sealed class MesIntegrationSettings : MesRestSettings
{
    public bool IsMockRest => Mode == MesIntegrationMode.MockRest;
    public bool IsUploadCapable => Mode is MesIntegrationMode.MockRest or MesIntegrationMode.Rest;
}

public sealed class TraceabilityPayload
{
    public string SchemaVersion { get; set; } = "1.0.0";
    public string IntegrationMode { get; set; } = "Mock REST";
    public string LotId { get; set; } = string.Empty;
    public string BoardModel { get; set; } = string.Empty;
    public string? SerialNumber { get; set; }
    public string StationId { get; set; } = string.Empty;
    public string OperatorId { get; set; } = string.Empty;
    public string Result { get; set; } = "REVIEW";
    public DateTime TimestampUtc { get; set; } = DateTime.UtcNow;
    public string DefectSummary { get; set; } = string.Empty;
    public string ImagePath { get; set; } = string.Empty;
    public string OverlayPath { get; set; } = string.Empty;
    public string InspectionEngine { get; set; } = string.Empty;
    public string ModelVersion { get; set; } = string.Empty;
    public double Confidence { get; set; }
    public double Score { get; set; }
    public string SourceNotice { get; set; } = "Mock MES integration payload generated by AOI Monitor PoC. Not production MES writeback.";
}

public sealed record MesUploadAttemptRecord(
    long Id,
    DateTime CreatedAtUtc,
    string Mode,
    string EndpointUrl,
    string PayloadPath,
    string Status,
    string Message,
    string OperatorId,
    string LotId,
    string BoardModel,
    string Result);

public sealed record MesSpoolQueueRecord(
    long Id,
    DateTime CreatedAtUtc,
    DateTime? LastAttemptAtUtc,
    DateTime? NextAttemptAtUtc,
    string PayloadType,
    string PayloadJson,
    string PayloadPath,
    string EndpointUrl,
    int RetryCount,
    int MaxRetryCount,
    string Status,
    string LastError,
    string OperatorId,
    string LotId,
    string BoardModel,
    string Result);

public sealed record MesSpoolRetrySummary(
    int Attempted,
    int Succeeded,
    int Failed);
