using System.IO;
using System.Text.Json;
using AOI_Monitor.Data;
using AOI_Monitor.Models;

namespace AOI_Monitor.Services;

public sealed record TraceabilityUploadOutcome(
    TraceabilityPayload Payload,
    string PayloadPath,
    IntegrationCommandResult Result);

public static class TraceabilityUploadService
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    public static async Task<TraceabilityUploadOutcome> UploadAsync(
        TraceabilityPayload payload,
        CancellationToken cancellationToken = default)
    {
        var settings = MesIntegrationSettingsService.Load();
        MesIntegrationSettingsService.ApplyIntegrationBoundary();
        payload.IntegrationMode = ToDisplay(settings.Mode);
        payload.SourceNotice = settings.Mode == MesIntegrationMode.MockRest
            ? "Mock MES REST payload generated by AOI Monitor PoC. Not production MES writeback."
            : "Production MES/ERP integration is not connected. Payload retained locally for traceability architecture review.";

        var payloadPath = WritePayload(payload);
        IntegrationCommandResult result;

        if (settings.Mode == MesIntegrationMode.MockRest)
        {
            result = await IntegrationBoundaryRegistry.MesClient.UploadTraceabilityAsync(payload, cancellationToken);
            if (string.IsNullOrWhiteSpace(settings.MockEndpointUrl) && result.Accepted)
            {
                result = result with
                {
                    Message = $"{result.Message} Local payload: {payloadPath}",
                };
            }
        }
        else
        {
            result = new IntegrationCommandResult(
                true,
                IntegrationConnectionStatus.Simulated,
                $"{ToDisplay(settings.Mode)}; payload written to local JSON only. Local payload: {payloadPath}");
        }

        AoiDatabase.RecordMesUploadAttempt(
            ToDisplay(settings.Mode),
            settings.MockEndpointUrl,
            payloadPath,
            result.Accepted ? "OK" : "ERROR",
            result.Message,
            payload.OperatorId,
            payload.LotId,
            payload.BoardModel,
            payload.Result);

        return new TraceabilityUploadOutcome(payload, payloadPath, result);
    }

    public static string WritePayload(TraceabilityPayload payload)
    {
        var root = Path.Combine(AoiDatabase.StorageRoot, "exports", "mes_mock");
        Directory.CreateDirectory(root);
        var safeLot = SafeFilePart(payload.LotId, "LOT");
        var safeResult = SafeFilePart(payload.Result, "RESULT");
        var path = Path.Combine(root, $"traceability_{safeLot}_{safeResult}_{DateTime.Now:yyyyMMdd_HHmmssfff}.json");
        File.WriteAllText(path, JsonSerializer.Serialize(payload, JsonOptions));
        return path;
    }

    public static string ToDisplay(MesIntegrationMode mode) => mode switch
    {
        MesIntegrationMode.MockRest => "Mock REST",
        MesIntegrationMode.FutureProduction => "Future Production Planned",
        _ => "Not Connected",
    };

    private static string SafeFilePart(string value, string fallback)
    {
        var text = string.IsNullOrWhiteSpace(value) ? fallback : value.Trim();
        foreach (var ch in Path.GetInvalidFileNameChars())
            text = text.Replace(ch, '_');
        return text.Replace(' ', '_');
    }
}
