using System.IO;
using System.Text.Json;
using AOI_Monitor.Data;
using AOI_Monitor.Models;

namespace AOI_Monitor.Services;

public sealed record TraceabilityUploadOutcome(
    TraceabilityPayload Payload,
    string PayloadPath,
    IntegrationCommandResult Result);

public static class TraceabilityUploadService
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    public static async Task<TraceabilityUploadOutcome> UploadAsync(
        TraceabilityPayload payload,
        CancellationToken cancellationToken = default)
    {
        var settings = MesIntegrationSettingsService.Load();
        MesIntegrationSettingsService.ApplyIntegrationBoundary();
        payload.IntegrationMode = ToDisplay(settings.Mode);
        payload.SourceNotice = settings.Mode switch
        {
            MesIntegrationMode.MockRest => "Mock/local MES payload generated by AOI Monitor PoC. Not production MES writeback.",
            MesIntegrationMode.Rest => "MES REST boundary enabled by local settings. Payload retained locally and posted to configured endpoint; secrets are not logged.",
            MesIntegrationMode.FutureProduction => "OPC UA adapter is a Stage 4 TODO. Payload retained locally for interface review.",
            _ => "MES/ERP integration is not connected. Payload retained locally for traceability architecture review.",
        };

        var payloadPath = WritePayload(payload);
        IntegrationCommandResult result;
        var endpoint = EndpointFor(settings);

        if (settings.Mode is MesIntegrationMode.MockRest or MesIntegrationMode.Rest)
        {
            result = await IntegrationBoundaryRegistry.MesClient.UploadTraceabilityAsync(payload, cancellationToken);
            if (settings.Mode == MesIntegrationMode.MockRest &&
                string.IsNullOrWhiteSpace(settings.MockEndpointUrl) &&
                result.Accepted)
            {
                result = result with
                {
                    Message = $"{result.Message} Local payload: {payloadPath}",
                };
            }

            if (settings.Mode == MesIntegrationMode.Rest && !result.Accepted)
            {
                var spoolId = SpoolTraceabilityPayload(payload, payloadPath, endpoint, settings, result.Message);
                result = result with { Message = $"{result.Message} Payload spooled for retry as item {spoolId}." };
            }
        }
        else
        {
            result = new IntegrationCommandResult(
                true,
                IntegrationConnectionStatus.Simulated,
                $"{ToDisplay(settings.Mode)}; payload written to local JSON only. Local payload: {payloadPath}");
        }

        AoiDatabase.RecordMesUploadAttempt(
            ToDisplay(settings.Mode),
            endpoint,
            payloadPath,
            result.Accepted ? "OK" : "ERROR",
            result.Message,
            payload.OperatorId,
            payload.LotId,
            payload.BoardModel,
            payload.Result);
        ExportVerificationService.RecordVerifiedExport(
            "MesTraceabilityPayload",
            payloadPath,
            result.Accepted ? "OK" : "ERROR",
            payload.OperatorId);

        return new TraceabilityUploadOutcome(payload, payloadPath, result);
    }

    public static Task<TraceabilityUploadOutcome> UploadInspectionResultAsync(
        AnalysisResult result,
        CancellationToken cancellationToken = default)
        => UploadAsync(BuildPayloadFromInspectionResult(result), cancellationToken);

    public static async Task<MesSpoolRetrySummary> RetryPendingMesUploadsAsync(
        int limit = 100,
        CancellationToken cancellationToken = default)
    {
        var settings = MesIntegrationSettingsService.Load();
        MesIntegrationSettingsService.ApplyIntegrationBoundary();
        var pending = AoiDatabase.GetPendingMesSpoolItems(limit);
        var attempted = 0;
        var succeeded = 0;
        var failed = 0;

        foreach (var item in pending)
        {
            cancellationToken.ThrowIfCancellationRequested();
            attempted++;

            IntegrationCommandResult result;
            try
            {
                result = item.PayloadType switch
                {
                    "UploadResultCommand" => await IntegrationBoundaryRegistry.MesClient.UploadResultAsync(
                        JsonSerializer.Deserialize<UploadResultCommand>(item.PayloadJson, JsonOptions)!,
                        cancellationToken),
                    "UploadImageCommand" => await IntegrationBoundaryRegistry.MesClient.UploadImageAsync(
                        JsonSerializer.Deserialize<UploadImageCommand>(item.PayloadJson, JsonOptions)!,
                        cancellationToken),
                    _ => await IntegrationBoundaryRegistry.MesClient.UploadTraceabilityAsync(
                        JsonSerializer.Deserialize<TraceabilityPayload>(item.PayloadJson, JsonOptions)!,
                        cancellationToken),
                };
            }
            catch (Exception ex) when (ex is JsonException or NotSupportedException or InvalidOperationException)
            {
                result = new IntegrationCommandResult(false, IntegrationConnectionStatus.Error, $"MES spool retry could not read payload: {ex.Message}");
            }

            AoiDatabase.RecordMesUploadAttempt(
                ToDisplay(settings.Mode),
                item.EndpointUrl,
                item.PayloadPath,
                result.Accepted ? "OK" : "ERROR",
                $"Retry spool item {item.Id}: {result.Message}",
                item.OperatorId,
                item.LotId,
                item.BoardModel,
                item.Result);

            if (result.Accepted)
            {
                succeeded++;
                AoiDatabase.DeleteMesSpoolItem(item.Id, result.Message);
            }
            else
            {
                failed++;
                AoiDatabase.RecordMesSpoolRetryFailure(item.Id, result.Message, settings.RetryBackoffMs);
            }
        }

        return new MesSpoolRetrySummary(attempted, succeeded, failed);
    }

    public static string WritePayload(TraceabilityPayload payload)
    {
        var root = Path.Combine(AoiDatabase.StorageRoot, "exports", "mes_mock");
        Directory.CreateDirectory(root);
        var safeLot = SafeFilePart(payload.LotId, "LOT");
        var safeResult = SafeFilePart(payload.Result, "RESULT");
        var path = Path.Combine(root, $"traceability_{safeLot}_{safeResult}_{DateTime.Now:yyyyMMdd_HHmmssfff}.json");
        File.WriteAllText(path, JsonSerializer.Serialize(payload, JsonOptions));
        return path;
    }

    public static string ToDisplay(MesIntegrationMode mode) => mode switch
    {
        MesIntegrationMode.MockRest => "Mock REST",
        MesIntegrationMode.Rest => "REST",
        MesIntegrationMode.FutureProduction => "Future Production Planned",
        _ => "Not Connected",
    };

    private static long SpoolTraceabilityPayload(
        TraceabilityPayload payload,
        string payloadPath,
        string endpoint,
        MesIntegrationSettings settings,
        string lastError)
    {
        var payloadJson = JsonSerializer.Serialize(payload, JsonOptions);
        return AoiDatabase.EnqueueMesSpoolItem(
            nameof(TraceabilityPayload),
            payloadJson,
            payloadPath,
            endpoint,
            settings.MaxRetryCount,
            lastError,
            payload.OperatorId,
            payload.LotId,
            payload.BoardModel,
            payload.Result);
    }

    private static TraceabilityPayload BuildPayloadFromInspectionResult(AnalysisResult result)
    {
        var defectSummary = result.Defects.Count == 0
            ? "No defects reported"
            : string.Join(
                "; ",
                result.Defects
                    .GroupBy(defect => string.IsNullOrWhiteSpace(defect.DefectType) ? "Unknown" : defect.DefectType)
                    .Select(group => $"{group.Key}={group.Count()}"));

        return new TraceabilityPayload
        {
            IntegrationMode = ToDisplay(MesIntegrationSettingsService.Load().Mode),
            LotId = result.LotId,
            BoardModel = result.BoardProgram,
            SerialNumber = result.BoardId,
            StationId = result.StationId,
            OperatorId = result.OperatorId,
            Result = result.Verdict,
            TimestampUtc = result.Timestamp.ToUniversalTime(),
            DefectSummary = $"{defectSummary}; score={result.DifferenceScore:F1}; confidence={result.Confidence:P0}; inspectionId={result.InspectionId}",
            ImagePath = result.SamplePath,
            OverlayPath = string.Empty,
            InspectionEngine = result.InspectionEngine,
            ModelVersion = result.ModelVersion,
            Confidence = result.Confidence,
            Score = result.DifferenceScore,
        };
    }

    private static string EndpointFor(MesIntegrationSettings settings)
    {
        if (settings.Mode == MesIntegrationMode.MockRest)
            return settings.MockEndpointUrl;

        if (settings.Mode != MesIntegrationMode.Rest)
            return string.Empty;

        var baseUrl = settings.BaseUrl.TrimEnd('/');
        var path = settings.UploadResultPath.StartsWith("/", StringComparison.Ordinal)
            ? settings.UploadResultPath
            : $"/{settings.UploadResultPath}";
        return $"{baseUrl}{path}";
    }

    private static string SafeFilePart(string value, string fallback)
    {
        var text = string.IsNullOrWhiteSpace(value) ? fallback : value.Trim();
        foreach (var ch in Path.GetInvalidFileNameChars())
            text = text.Replace(ch, '_');
        return text.Replace(' ', '_');
    }
}
